# Generated by Django 3.1 on 2020-09-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='icon',
            field=models.CharField(default='fa', max_length=50),
            preserve_default=False,
        ),
    ]
