# Generated by Django 3.1 on 2020-09-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_post_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='icon',
            field=models.CharField(max_length=40),
        ),
    ]
