# Generated by Django 3.1 on 2020-09-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20200909_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='icon',
        ),
    ]
