# Generated by Django 3.1 on 2020-09-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_portfoliopost'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopost',
            name='link',
            field=models.CharField(default='www.google.com', max_length=50),
            preserve_default=False,
        ),
    ]
